const symbols = {
    zoom: "􀅊",
    macWindow: "􀏜",
    fullscreen: "􀏃",
    splitScreen: "􀧈",
    app: "•",
    bsp: "􀏝",
    float: "􀇴",
    stack: "􀏭",
    pip: "􀭳",
    pipTopLeft: "􀭳",
    pipTopRight: "􀭴",
    pipBottomLeft: "􀭵",
    pipBottomRight: "􀭶",
    display: "􀢹",
    space: "􀋑",
    laptop: "􀟛",
    tablet: "􀏃",
    cpu: "􀫥",
    work: "􀥏",
    overheat: "􀙭",
    battery: [
        "􀛪",
        "􀛩",
        "􀺶",
        "􀺸",
        "􀛨"
    ],
    batteryCharging: "􀢋",
    power: "􀋦",
    powerPassthrough: "􀋨",
    powerSaving: "􀥳",
    clock: "􀐫",
    calendar: "􀉉",
    numbers: [
        "􀃈",
        "􀃊",
        "􀃌",
        "􀃎",
        "􀃐",
        "􀃒",
        "􀃔",
        "􀃖",
        "􀃘",
        "􀃚",
        "􀔳",
        "􀔴",
        "􀔵",
        "􀔶",
        "􀔷",
        "􀔸",
        "􀔹",
        "􀔺",
        "􀔻",
        "􀔼",
        "􀔽",
    ]
}
export default symbols;
